### PR TITLE
Fix openstudio measure tests

### LINKED ISSUE #77: Fix test_with_openstudio model failures

### PR DESCRIPTION
**Pull request by tanushree04**
### Pull Request Description
Fixes openstudio measure tests

### Checklist (Delete lines that don't apply)

- [ ] Unit tests have been added or updated
- [ ] All ci tests pass (green)
- [ ] An [ISSUE](https://github.com/urbanopt/urbanopt-reporting-gem/issues) has been created that this is addressing. Issues will get added to the Change Log when the change_log.rb script is run.
- [ ] This branch is up-to-date with develop

### CODE REVIEW

**Comment by tanushree04** [comment]
@rawadelkontar, The following lines in the measure are failing in the measure test:

This is the error - `RuntimeError: Optional not initialized`


https://github.com/urbanopt/urbanopt-reporting-gem/pull/78/files#diff-e83b4234feb824513adeaa99c07ecf935a318e4522d64b2a3bd9ebdd9a7d3ffbR540

https://github.com/urbanopt/urbanopt-reporting-gem/pull/78/files#diff-e83b4234feb824513adeaa99c07ecf935a318e4522d64b2a3bd9ebdd9a7d3ffbL974

**Comment by tanushree04** [comment]
@nllong @vtnate , This [line](https://github.com/urbanopt/urbanopt-reporting-gem/blob/c5ae422c34a3ad44a7147ec47b13e504da38f9db/lib/measures/export_modelica_loads/tests/export_modelica_loads_test.rb#L119) in the ExportModelicaLoadsTest is failing. The [OSM](https://github.com/urbanopt/urbanopt-reporting-gem/blob/develop/lib/measures/export_modelica_loads/tests/example_model.osm) used for the test may need to be updated or replaced. 

This is the error I see when I open it in the OpenStudio App (it is OS -v 3.1.0) :


Model with Version 3.1.0 IDD is not valid to draft strictness level.
 
The collection is INVALID at strictness level 'Draft', because of the errors:
Field      level data error of type DataType          .
Error is in an object of type 'OS:Construction:AirBoundary', named 'Air Wall', in field 3.
Additional information about the error type: field-level data is of an incorrect type.
Field      level data error of type DataType          .
Error is in an object of type 'OS:Connection', named '{e07e3e73-3473-4218-a6e5-d652954768c5}', in field 3.
Additional information about the error type: field-level data is of an incorrect type.
Field      level data error of type DataType          .
Error is in an object of type 'OS:PortList', named '{e07e3e73-3473-4218-a6e5-d652954768c5}', in field 2.
Additional information about the error type: field-level data is of an incorrect type.

**Comment by vtnate** [comment]
> @nllong @vtnate , This [line](https://github.com/urbanopt/urbanopt-reporting-gem/blob/c5ae422c34a3ad44a7147ec47b13e504da38f9db/lib/measures/export_modelica_loads/tests/export_modelica_loads_test.rb#L119) in the ExportModelicaLoadsTest is failing. The [OSM](https://github.com/urbanopt/urbanopt-reporting-gem/blob/develop/lib/measures/export_modelica_loads/tests/example_model.osm) used for the test may need to be updated or replaced.

Huh. The original that this measure is copied from (is there an alternative to copy/pasting that measure?) is [here](https://github.com/urbanopt/openstudio-prototype-loads/tree/develop/measures/export_modelica_loads) and it looks like it hasn't changed in quite a while.

Maybe that has always been failing? CI is showing green, we might have just missed this in our earlier work.

**Comment by kflemin** [comment]
@vtnate, this has been silently failing on the reporting-gem CI for a while and we'd like to get it passing

**Comment by nllong** [comment]
I'm happy to look into fixing this, but maybe @vtnate or @amyeallen1 can do it faster?

**Comment by amyeallen1** [comment]
Hi, if the goal of using this measure is to get loads in a CSV format, I'd recommend using the Export Time Series Loads CSV measure, which I adapted from this original measure that Nick wrote, and have been actively maintaining. If .mos files are needed, then this Export Modelica Loads is the measure to use. I believe this measure is still in the original form that Nick wrote, but I'm happy to look into updating the test next week.  @kflemin @vtnate @nllong @tanushree04

**Comment by vtnate** [comment]
@amyeallen1 This measure outputs mos files from the SDK for use by the DES CLI. There were two problems here:

1. We hadn't updated the example osm file when the original was updated in January
2. We needed an additional `require` statement to make the measure work

**Review by kflemin — APPROVED** [review]

**Pull request merged**
